### ISSUE TITLE
[bug] Missing v0.6.11 release.

### ISSUE THREAD

**Issue by henryiii** [cheshirekow/cmake-format-precommit#2]
Is it possible to combine this repo with the cmake-format one? I know at least Black does it all in one repo (see https://black.readthedocs.io/en/stable/version_control_integration.html). They are sadly out of sync - I copied and pasted from here: https://cmake-format.readthedocs.io/en/latest/installation.html#pre-commit :

```yaml
repo: https://github.com/cheshirekow/cmake-format-precommit
rev: v0.6.11
hooks:
- id: cmake-format
```

And got an error about v0.6.11 not existing, since there's no release here.

**Comment by henryiii** [comment]
@asottile might know if it's possible?

Also, is there a nice way to ask for other requirements in the config, like mypy does? I assume this isn't natively going to get yaml. Edit: `additional_dependencies` might work, will try that once I have a config file. Edit: Works great!

**Comment by asottile** [comment]
yes, and usually it makes more sense to include the `.pre-commit-hooks.yaml` file as part of the main repository -- unclear to me why they are separate here ?  maybe @cheshirekow can comment to that

this would then pick up the tags automatically as they are created in the parent repository

**Comment by cheshirekow** [comment]
> Is it possible to combine this repo with the cmake-format one? 

It is possible but [I prefer this approach][1]. 

> They are sadly out of sync - I copied and pasted from here:

I would love to get the whole release pipeline automated, but so far only some of it is. pypi upload, vscode upload, this repository, and dockerhub are still manual release. 

> Also, is there a nice way to ask for other requirements in the config, like mypy does?

I think [this person][2] had a solution for that. 

[1]: https://github.com/cheshirekow/cmake_format/pull/44
[2]: https://github.com/cheshirekow/cmake-format-precommit/issues/1

**Comment by henryiii** [comment]
@asottile Is there a way to have a `.pre-commit-hooks.yaml` in the main repository that doesn't install from setup.py, but installs from pypi instead? That seems to be the issue IIUC.

**Comment by henryiii** [comment]
```yaml
- repo: https://github.com/cheshirekow/cmake-format-precommit
  rev: v0.6.10
  hooks:
  - id: cmake-format
    additional_dependencies: [pyyaml]
```

Works perfectly.

PyPI releases are [really easy](https://scikit-hep.org/developer/gha_pure#distribution-pure-python-wheels), but pushing between repositories takes a bit more setup. (Doable though, it's how most website generator are setup, I do it [here](https://github.com/iris-hep/iris-hep.github.io-source/blob/master/.github/workflows/ci.yml) at least, though it's inside a GH pages specific action in that case.)

**Comment by asottile** [comment]
> @asottile Is there a way to have a `.pre-commit-hooks.yaml` in the main repository that doesn't install from setup.py, but installs from pypi instead? That seems to be the issue IIUC.

that wouldn't actually solve anything because you'd still need to bump the version

fwiw pre-commit works best when it installs from git

**Comment by henryiii** [comment]
I'm guessing something like bump version is being used, as the version was updated on the page that described the use of pre-commit, so having a manual version might not be that bad. (Speaking for someone else on something I know nothing about, so take that for what it's worth)

**Comment by henryiii** [comment]
PS: You could provide both, one from the main repo that installs from git, and one that installs from pip. :)

**Comment by tueda** [comment]
Now, again `v0.6.13` is missing...

**Comment by cheshirekow** [comment]
Are you sure? Tag looks like [it is there][1] and [travis said][2] it was up to date during the release job.

[1]: https://github.com/cheshirekow/cmake-format-precommit/tree/v0.6.13
[2]: https://travis-ci.com/github/cheshirekow/cmake_format/jobs/375477125#L1086

**Comment by tueda** [comment]
Oh, I found `pre-commit autoupdate` failed to pick up `v0.6.13` and saw the commit message `update to 0.6.11` on the `master` branch. But, you are right: indeed `v0.6.13` was there, which is not on the `master` branch. Sorry for the noise.

**Comment by cheshirekow** [comment]
Release is now automated so closing this.
