### ISSUE TITLE
Tags on the master branch

### ISSUE THREAD

**Issue by tueda** [cheshirekow/cmake-format-precommit#3]
The [`pre-commit autoupdate` command](https://pre-commit.com/#updating-hooks-automatically) does not pick up versions that are not on the default branch.

Would you please merge `v0.6.13` into the `master` branch?

After I commented on [the other issue](https://github.com/cheshirekow/cmake-format-precommit/issues/2#issuecomment-688001982), I found a similar thing happened to `isort` (pre-commit/pre-commit#1555), and the solution was just putting tags on the default branch (PyCQA/isort#1371).

**Comment by cheshirekow** [comment]
> The pre-commit autoupdate command does not pick up versions that are not on the default branch.

Oh thats weird. Ok pushed.

**Comment by tueda** [comment]
Thank you. Now `pre-commit autoupdate` correctly upgrades `cmake-format-precommit` to `v0.6.13`.
